# <img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 15px; height: 80px">

# Project 4

###  Big Query, SQL, Classification

---

### The Data

There are 5 individual tables that have the information, contained in a Google BigQuery database.  The setup info for BigQuery is located on our DSI wiki.  You will have to query with SQL, the dataset in order to complete this project.

The tables, with cooresonding attributes that exist are:

### businesses
- business_id: unique business identifier
- name: name of the business
- review_count: number of reviews per business
- city: city business resides in
- stars: average rating
- categories: categories the business falls into (can be one or multiple)
- latitude
- longitude
- neighborhoods: neighborhoods business belongs to
- variable: "property" of the business (a tag)
- value: True/False for the property

### reviews
- user_id: unique user identifier
- review_id: unique review identifier
- votes.cool: how many thought the review was "cool"
- business_id: unique business id the review is for
- votes.funny: how many thought the review was funny
- stars: rating given
- date: date of review
- votes.useful: how many thought the review was useful
- ... 100 columns of counts of most common 2 word phrases that appear in reviews in this review

### users
- yelping_since: signup date
- compliments.plain: # of compliments "plain"
- review_count: # of reviews:
- compliments.cute: total # of compliments "cute"
- compliments.writer: # of compliments "writer"
- compliments.note: # of compliments "note" (not sure what this is)
- compliments.hot: # of compliments "hot" (?)
- compliments.cool: # of compliments "cool"
- compliments.profile: # of compliments "profile"
- average_stars: average rating
- compliments.more: # of compliments "more"
- elite: years considered "elite"
- name: user's name
- user_id: unique user id
- votes.cool: # of votes "cool"
- compliments.list: # of compliments "list"
- votes.funny: # of compliments "funny"
- compliments.photos: # of compliments "photos"
- compliments.funny: # of compliments "funny"
- votes.useful: # of votes "useful"

### checkins
- business_id: unique business identifier
- variable: day-time identifier of checkins (0-0 is Sunday 0:00 - 1:00am,  for example)
- value: # of checkins at that time

### tips
- user_id: unique user identifier
- business_id: unique business identifier
- likes: likes that the tip has
- date: date of tip
- ... 100 columns of counts of most common 2 word phrases that appear in tips in this tip


The reviews and tips datasets in particular have parsed "NLP" columns with counts of 2-word phrases in that review or tip (a "tip", it seems, is some kind of smaller review).

The user dataset has a lot of columns of counts of different compliments and votes. We're not sure whether the compliments or votes are by the user or for the user.

Full details about this dataset area located here:
https://bigquery.cloud.google.com/dataset/bigquery-dsi-dave:yelp_arizona

---


If you look at the website, or the full data, you'll see I have removed pieces of the data and cut it down quite a bit. This is to simplify it for this project. Specifically, business are limited to be in these cities:

- Phoenix
- Surprise
- Las Vegas
- Waterloo

Apparently there is a city called "Surprise" in Arizona. 

Businesses are also restricted to at least be in one of the following categories, because we thought the mix of them was funny:

- Airports
- Breakfast & Brunch
- Bubble Tea
- Burgers
- Bars
- Bakeries
- Breweries
- Cafes
- Candy Stores
- Comedy Clubs
- Courthouses
- Dance Clubs
- Fast Food
- Museums
- Tattoo
- Vape Shops
- Yoga
    
---

### Project requirements

**You will be performing 4 different sections of analysis, like in the last project.**

Remember that classification targets are categorical and regression targets are continuous variables.

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 1. Load your dataset(s) / setup / configure GBQ connection

---

Information about this dataset is located here:


**If you haven't done so, setup a project with the Google developer portal, following the directions here: [Getting Started with BigQuery](https://github.com/ga-students/DSI-SF-4/wiki/Getting-Started-with-BigQuery)**

In [2]:
import pandas as pd
import seaborn as sns

%matplotlib inline

project_id = "bigquery-dsi-amlanlimaye"

table_names = ['businesses', 'reviews', 'users', 'checkins', 'tips']

for tbl_name in table_names:
    globals()[tbl_name] = pd.read_gbq("SELECT * FROM [bigquery-dsi-dave:yelp_arizona.{0}] LIMIT 20000".format(tbl_name), project_id=project_id)

Requesting query... ok.
Query running...
Query done.
Processed: 25.2 Mb

Retrieving results...
Got 20000 rows.

Total time taken 6.42 s.
Finished at 2016-12-20 08:27:39.
Requesting query... ok.
Query running...
Query done.
Processed: 277.3 Mb

Retrieving results...
  Got page: 1; 16.0% done. Elapsed 8.32 s.
  Got page: 2; 32.0% done. Elapsed 12.57 s.
  Got page: 3; 49.0% done. Elapsed 17.66 s.
  Got page: 4; 65.0% done. Elapsed 26.17 s.
  Got page: 5; 81.0% done. Elapsed 30.52 s.
  Got page: 6; 97.0% done. Elapsed 35.59 s.
  Got page: 7; 100.0% done. Elapsed 36.84 s.
Got 20000 rows.

Total time taken 41.74 s.
Finished at 2016-12-20 08:28:21.
Requesting query... ok.
Query running...
Query done.
Processed: 15.2 Mb

Retrieving results...
  Got page: 1; 83.0% done. Elapsed 8.39 s.
  Got page: 2; 100.0% done. Elapsed 11.34 s.
Got 20000 rows.

Total time taken 12.47 s.
Finished at 2016-12-20 08:28:34.
Requesting query... ok.
Query running...
Query done.
Processed: 9.8 Mb

Retrieving results...
Got 20000 rows.

Total time taken 2.5 s.
Finished at 2016-12-20 08:28:42.
Requesting query... ok.
Query running...
Query done.
Processed: 84.0 Mb

Retrieving results...
  Got page: 1; 17.0% done. Elapsed 8.88 s.
  Got page: 2; 34.0% done. Elapsed 12.2 s.
  Got page: 3; 50.0% done. Elapsed 16.01 s.
  Got page: 4; 67.0% done. Elapsed 20.19 s.
  Got page: 5; 84.0% done. Elapsed 25.62 s.
  Got page: 6; 100.0% done. Elapsed 31.44 s.
Got 20000 rows.

Total time taken 35.93 s.
Finished at 2016-12-20 08:29:18.

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 2. Constructing a "profile" for Las Vegas

---

Yelp is interested in building out what they are calling "profiles" for cities. They want you to start with just Las Vegas to see what a prototype of this would look like. Essentially, they want to know what makes Las Vegas distinct from the other four.

Use the data you have to predict Las Vegas from the other variables you have. You should not be predicting the city from any kind of location data or other data perfectly associated with that city (or another city).

You may use any classification algorithm you deem appropriate, or even multiple models. You should:

1. Build at least one model predicting Las Vegas vs. the other cities.
- Validate your model(s).
- Interpret and visualize, in some way, the results.
- Write up a "profile" for Las Vegas. This should be a writeup converting your findings from the model(s) into a human-readable description of the city.

*Research location data to find the city targets.*

In [9]:
businesses.head()

,business_id,name,review_count,city,stars,categories,latitude,longitude,neighborhoods,variable,value
0,--jFTZmywe7StuZ2hEjxyA,Subway,7,Las Vegas,3.5,"['Fast Food', 'Sandwiches', 'Restaurants']",36.118819,-115.182005,[],attributes.Takes Reservations,False
1,--jFTZmywe7StuZ2hEjxyA,Subway,7,Las Vegas,3.5,"['Fast Food', 'Sandwiches', 'Restaurants']",36.118819,-115.182005,[],attributes.Good For.dessert,False
2,--jFTZmywe7StuZ2hEjxyA,Subway,7,Las Vegas,3.5,"['Fast Food', 'Sandwiches', 'Restaurants']",36.118819,-115.182005,[],attributes.Take-out,True
3,--jFTZmywe7StuZ2hEjxyA,Subway,7,Las Vegas,3.5,"['Fast Food', 'Sandwiches', 'Restaurants']",36.118819,-115.182005,[],attributes.Has TV,False
4,--jFTZmywe7StuZ2hEjxyA,Subway,7,Las Vegas,3.5,"['Fast Food', 'Sandwiches', 'Restaurants']",36.118819,-115.182005,[],attributes.Good For.breakfast,True

In [10]:

checkins.head()

              business_id          variable value
0  0kZ4aYmqf5fzTt9Yvz8Kvw  checkin_info.0-0   1.0
1  PttpsvUJJiIyLd3ZjSnjCQ  checkin_info.0-0   1.0
2  3fA43apyr5i8PAm0Az04hQ  checkin_info.0-0   1.0
3  S3iZm7-MKPhvXWZRPqC_Og  checkin_info.0-0   1.0
4  _I-hcsM-TFQkBgSjpk7JLQ  checkin_info.0-0   1.0

In [11]:
reviews.head()

,user_id,review_id,votes_cool,business_id,votes_funny,stars,date,votes_useful,minutes_10,minutes_15,...,service_great,staff_friendly,super_friendly,sweet_potato,tasted_like,time_vegas,try_place,ve_seen,ve_tried,wait_staff
0,xj0fNFa-hIk7cIsNiEwdbQ,uVN4bnhWA1h6vq5ppwPl9A,0,tirnCFwpur4bdtBizlUAnQ,1,1,2012-05-07,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,pwe_eui0_v-OpYAmwxFuqA,LhF0PvTr5VsLALPxzSHeYQ,1,J7DYRCtU9Tdtja5c7k1sjQ,0,1,2015-12-18,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9Q9Sxx9Uc_Wfan8cb9j4zA,FOBwjhlSc3o5P9K4VNCB1Q,0,DXut5Gke7XM6oAvoFahFNg,0,1,2011-08-05,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ckLRpYBIWxFWNr4Rwm55kg,a6VOJ_vNiGQ4jUZ3tgiejw,0,ttLtsY1S2Angj6hvEdzwDQ,0,1,2015-09-25,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,XS8n2P2lZddLK9PjV__w8A,fbatI_Zg1QQj4Yo1uW0fNw,0,ttLtsY1S2Angj6hvEdzwDQ,0,1,2015-10-02,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
tips.head()

,user_id,business_id,likes,date,hours_24,amazing_food,animal_style,awesome_food,awesome_place,awesome_service,...,service_good,service_great,slow_service,staff_friendly,staff_great,steak_eggs,super_friendly,sweet_potato,velvet_pancakes,worth_wait
0,p7IMf1yOOISqwzHGqsMyqA,AKyTwyfCRHAQ-W4oMRKVtA,0,2014-05-23,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,67gR8iICAL7WQQGuVxHToA,AKyTwyfCRHAQ-W4oMRKVtA,0,2011-09-07,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,TgAz40uH7rSrIp-PZnqrHQ,AKyTwyfCRHAQ-W4oMRKVtA,0,2012-06-09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,hMXsiY0JWAVi7K1TeoFqng,AKyTwyfCRHAQ-W4oMRKVtA,0,2012-11-27,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,TgAz40uH7rSrIp-PZnqrHQ,AKyTwyfCRHAQ-W4oMRKVtA,0,2010-10-27,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Can use 'name' in businesses table to look up name of business by business_id

# Columns that might be useful in predicting city = 'Las Vegas' (0/1):

# businesses table: business_id(for joins), city, stars, attributes.X
# checkins table: business_id, variable, value
# reviews table: business_id, votes.cool, votes.funny, votes.useful, bottle_service
# tips table: business_id, likes

In [ ]:
# Converting 'businesses' table into a wide table

businesses_wide = pd.pivot_table(businesses, index=['business_id','city'], columns='variable', values='value').reset_index()

In [16]:
# Making checkins data usable for LV classification model

checkins.variable.value_counts()

checkin_info.0-6    1229
checkin_info.0-5    1168
checkin_info.1-6    1006
checkin_info.1-5     918
checkin_info.0-4     910
checkin_info.0-0     837
checkin_info.0-3     826
checkin_info.0-2     785
checkin_info.0-1     729
checkin_info.2-5     697
checkin_info.2-6     688
checkin_info.1-4     682
checkin_info.1-3     620
checkin_info.1-0     606
checkin_info.1-2     564
checkin_info.3-6     546
checkin_info.1-1     520
checkin_info.2-4     513
checkin_info.3-5     504
checkin_info.2-3     441
checkin_info.2-0     429
checkin_info.4-6     396
checkin_info.2-2     393
checkin_info.2-1     371
checkin_info.4-5     367
checkin_info.3-4     344
checkin_info.3-0     323
checkin_info.5-0     285
checkin_info.5-1     262
checkin_info.4-4     261
checkin_info.3-3     258
checkin_info.3-2     255
checkin_info.4-0     242
checkin_info.3-1     240
checkin_info.4-2     230
checkin_info.4-3     225
checkin_info.4-1     210
checkin_info.5-2     120
Name: variable, dtype: int64

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 3. Different categories of ratings

---

Yelp is finally ready to admit that their rating system sucks. No one cares about the ratings, they just use the site to find out what's nearby. The ratings are simply too unreliable for people. 

Yelp hypothesizes that this is, in fact, because different people tend to give their ratings based on different things. They believe that perhaps some people always base their ratings on quality of food, others on service, and perhaps other categories as well. 

1. Do some users tend to talk about service more than others in reviews/tips? Divide up the tips/reviews into more "service-focused" ones and those less concerned with service.
2. Create two new ratings for businesses: ratings from just the service-focused reviews and ratings from the non-service reviews.
3. Construct a regression model for each of the two ratings. They should use the same predictor variables (of your choice). 
4. Validate the performance of the models.
5. Do the models coefficients differ at all? What does this tell you about the hypothesis that there are in fact two different kinds of ratings?

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 4. Identifying "elite" users

---

Yelp, though having their own formula for determining whether a user is elite or not, is interested in delving deeper into what differentiates an elite user from a normal user at a broader level.

Use a classification model to predict whether a user is elite or not. Note that users can be elite in some years and not in others.

1. What things predict well whether a user is elite or not?
- Validate the model.
- If you were to remove the "counts" metrics for users (reviews, votes, compliments), what distinguishes an elite user, if anything? Validate the model and compare it to the one with the count variables.
- Think of a way to visually represent your results in a compelling way.
- Give a brief write-up of your findings.

<img src="http://imgur.com/GCAf1UX.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 5. Find something interesting on your own

---

You want to impress your superiors at Yelp by doing some investigation into the data on your own. You want to do classification, but you're not sure on what.

1. Create a hypothesis or hypotheses about the data based on whatever you are interested in, as long as it is predicting a category of some kind (classification).
2. Explore the data visually (ideally related to this hypothesis).
3. Build one or more classification models to predict your target variable. **Your modeling should include gridsearching to find optimal model parameters.**
4. Evaluate the performance of your model. Explain why your model may have chosen those specific parameters during the gridsearch process.
5. Write up what the model tells you. Does it validate or invalidate your hypothesis? Write this up as if for a non-technical audience.

<img src="http://imgur.com/GCAf1UX.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 6. ROC and Precision-recall

---

Some categories have fewer overall businesses than others. Choose two categories of businesses to predict, one that makes your proportion of target classes as even as possible, and another that has very few businesses and thus makes the target varible imbalanced.

1. Create two classification models predicting these categories. Optimize the models and choose variables as you see fit.
- Make confusion matrices for your models. Describe the confusion matrices and explain what they tell you about your models' performance.
- Make ROC curves for both models. What do the ROC curves describe and what do they tell you about your model?
- Make Precision-Recall curves for the models. What do they describe? How do they compare to the ROC curves?
- Explain when Precision-Recall may be preferable to ROC. Is that the case in either of your models?